In [1]:
def greet(name):
    name = name.upper()
    print(f"Hello {name}")

In [2]:
greet("Iva")

Hello IVA


In [3]:
employee = "Salim"
greet(employee)

Hello SALIM


# Hands-on practice: Mastering Python Functions

In [4]:
# Exercise 1
def calculate_area(width, height):
    return width*height

calculate_area(2,5)

10

In [5]:
# Exercise 2
def introduction(name, age=25):
    print(f"This is {name}, and his/her age is {age} years old.")

introduction("Iva",24)

This is Iva, and his/her age is 24 years old.


In [6]:
# Exercise 3
def first_last(my_list: list):
    first_elem = my_list[0]
    last_elem = my_list[len(my_list)-1]
    print(f"First element is {first_elem}, and last element is {last_elem}")
    return first_elem, last_elem

In [7]:
my_list = [1,2,3,4]
first_last(my_list)

First element is 1, and last element is 4


(1, 4)

# Modules and Libraries

In [8]:
!pip install numpy

In [9]:
import numpy as np

In [10]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [11]:
np.arange(start=100,stop=200,step=33)

array([100, 133, 166, 199])

In [12]:
import math

math.sqrt(16)

4.0

In [13]:
import datetime as dt
dt.datetime.now().strftime("%d/%m/%Y %H:%M")

'18/02/2026 11:25'

In [14]:
from random import randint
randint(1,10)

3

In [15]:
import requests
response = requests.get("http://httpbin.org/ip")
print(response.text)

{
  "origin": "185.11.154.62"
}



In [16]:
import os
os.listdir()

['my_data.csv', '.ipynb_checkpoints', 'Class Notes Day 3.ipynb']

In [17]:
os.getcwd()

'/Users/ivadodiikj/Desktop/uni/Python/mds/Day 3'

In [18]:
import sys 
print(f'Python version: {sys.version}')

Python version: 3.11.14 (main, Oct 21 2025, 18:27:30) [Clang 20.1.8 ]


In [19]:
import csv
with open("my_data.csv") as f:
    reader = csv.reader(f) # iterator
    for row in reader:
        print(row)

['id', 'name', 'age', 'city']
['1', 'Alice', '34', 'New York City']
['2', 'Bob', '28', 'LA']
['3', 'Charlie', '21', 'Chicago']
['4', 'Diana', '25', 'Houston']
['5', 'Evan', '29', 'Phoenix']


In [20]:
import csv
from io import StringIO

with open("my_data.csv") as f:
    reader = csv.DictReader(f) # iterator
    for row in reader:
        print(f'{row["name"]}, {row["age"]}')

Alice, 34
Bob, 28
Charlie, 21
Diana, 25
Evan, 29


In [21]:
import tkinter as tk

root = tk.Tk()
root.title("My first TKinter Window")

''

In [22]:
welcome_label = tk.Label(root, text="Welcome to Tkinter")
welcome_label.pack()

In [23]:
def on_button_click():
    welcome_label.config(text="Button Clicked!") 

In [24]:
click_me_button = tk.Button(root, text="Click Me", command=on_button_click)

In [25]:
click_me_button.pack()

In [26]:
# root.mainloop()

In [20]:
import numpy as np

In [36]:
arr1 = np.array([1,2,3,4,5])

In [37]:
arr1.mean()

np.float64(3.0)

In [38]:
arr1.std()

np.float64(1.4142135623730951)

In [39]:
print(f"Multiplication by 2 is: {arr1*2}")

Multiplication by 2 is: [ 2  4  6  8 10]


In [33]:
multi_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [34]:
multi_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
multi_arr * 4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [42]:
print(f"Inverted matrix\n{multi_arr.T}")

Inverted matrix
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [44]:
print(f"shape of this matrix: {(multi_arr.T).shape}")

shape of this matrix: (3, 4)


In [47]:
random_integers = np.random.randint(100, 200, 20) 

In [48]:
even_numbers = random_integers[random_integers % 2 == 0] 

In [49]:
even_numbers

array([116, 162, 182, 134, 140, 182, 146, 186, 166, 112, 160, 168])

In [50]:
sliced_array = even_numbers[2:10] 

In [51]:
sliced_array

array([182, 134, 140, 182, 146, 186, 166, 112])

In [52]:
array1 = np.random.randint(1,10,4)
array2 = np.random.randint(1,10,4)

In [54]:
print(array1)
print(array2)

[3 7 3 7]
[9 1 4 3]


In [53]:
print(f"The sum of the two arrays is {array1+array2}")

The sum of the two arrays is [12  8  7 10]


In [55]:
print(f"The product of the two arrays is {array1*array2}")

The product of the two arrays is [27  7 12 21]


In [56]:
print(f"The difference of the two arrays is {array1-array2}")

The difference of the two arrays is [-6  6 -1  4]


In [57]:
np.dot(array1,array2)

np.int64(67)

In [61]:
dataset = np.genfromtxt("data.csv", delimiter=',',skip_header=1)

In [62]:
dataset

array([[99., 36., 31., ..., 27., 80., 42.],
       [75., 81., 29., ..., 55., 99., 28.],
       [36., 84., 69., ...,  6., 38., 37.],
       ...,
       [56., 87.,  3., ..., 65.,  9., 38.],
       [18., 44., 95., ..., 97., 81., 87.],
       [ 3., 68., 99., ..., 27., 44.,  9.]], shape=(72, 16))

In [63]:
dataset.sum()

np.float64(57598.0)

In [64]:
column_index=0
column_data = dataset[:,column_index]

In [65]:
column_data

array([99., 75., 36., 62., 78., 58., 29., 63., 71., 60., 48., 44., 23.,
       47., 12., 79., 36., 67., 34., 71., 22., 70., 96., 87., 75., 81.,
       79., 39.,  8., 71., 52., 80.,  2., 45., 67., 32., 76.,  9., 86.,
       77., 22., 23., 81., 78., 22., 23., 25.,  8., 46., 92., 10., 84.,
       49., 77., 77., 88., 37., 49., 20., 66., 81., 81., 45., 40., 23.,
       74., 89., 13., 93., 56., 18.,  3.])